name: beer_hunter
description: ''
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  dio: ^5.4.0
  kiwi: ^4.1.0
  provider: ^6.1.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
